# Form implementation generated from reading ui file 'pages/cashReportPage.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget
from datetime import datetime, timedelta
from PyQt6.QtCore import Qt, QDate
from models import BuyerProfileModel
from pages.buyerProfileView import BuyerProfileView
from features.data_save_signals import data_save_signals
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base
from ui.buyerProfiles_ui import buyerProfiles_ui

class buyerProfiles(QWidget):
    def __init__(self):
        super().__init__()
        self.setup_database()  # First setup database
        self.ui = buyerProfiles_ui()
        self.ui.setupUi(self)
        self.setup_ui()


    def setup_ui(self):
        self.ui.tableWidget.horizontalHeader().setDefaultSectionSize(135)
        self.ui.tableWidget.horizontalHeader().setMinimumSectionSize(135)

        # Set current date ****************
        self.ui.startDateInput.setDisplayFormat("dd/MM/yyyy")
        self.ui.endDateInput.setDisplayFormat("dd/MM/yyyy")
        self.today_date_raw = datetime.now()
        self.today_date = self.today_date_raw.strftime("%d/%m/%Y").lstrip('0').replace('/0', '/')
        self.qdate_today = QDate.fromString(self.today_date, "d/M/yyyy")
        self.ui.startDateInput.setDate(self.qdate_today)
        self.ui.endDateInput.setDate(self.qdate_today)

        data_save_signals.data_saved.connect(self.filter_data)
        self.filter_data()
        self.ui.filterBtn.clicked.connect(self.filter_data)

        # ************ Autocomplete *****************************
        self.auto_completer()
        data_save_signals.data_saved.connect(lambda: self.auto_completer())
        # *************** end autocomplete *******************************

        self.ui.buyerFilterInput.textChanged.connect(lambda : self.make_capital(self.ui.buyerFilterInput))

    def setup_database(self):

        self.Base = declarative_base()
        self.engine = create_engine('sqlite:///business.db')
        self.Base.metadata.create_all(self.engine)
        self.Session = sessionmaker(bind=self.engine)

    def auto_completer(self):
        """Refresh the QCompleter with the latest seller names."""
        self.all_name = self.get_all_names()
        self.completer = QtWidgets.QCompleter(self.all_name, self)    # QT object parameter memoPageMain
        self.completer.setCaseSensitivity(Qt.CaseSensitivity.CaseInsensitive)
        self.ui.buyerFilterInput.setCompleter(self.completer)   # change input field

    def get_all_names(self):
        """Fetch all seller names from the database for autocomplete."""
        session = self.Session()
        name_entires = session.query(BuyerProfileModel).all()     # change Model name
        session.close()
        return [name_entry.buyer_name for name_entry in name_entires]    # change field name

    def make_capital(self, element):
        element.textChanged.disconnect()
        element.setText(element.text().title())
        element.textChanged.connect(lambda: self.make_capital(element))

    def filter_data(self):
        try:
            start_date = self.ui.startDateInput.date().toPyDate()
            start_date = start_date - timedelta(days=7)
            end_date = self.ui.endDateInput.date().toPyDate()
            buyer_filter = self.ui.buyerFilterInput.text()


            # Retrieve data from the database
            session = self.Session()
            query = session.query(BuyerProfileModel).filter(BuyerProfileModel.date.between(start_date, end_date))
            query = query.filter(BuyerProfileModel.buyer_name.ilike(f"%{buyer_filter}%"))
            buyers = query.all()
            # Clear existing table data
            self.ui.tableWidget.clearContents()
            self.ui.tableWidget.setRowCount(0)

            # Populate the table with queried data
            row = 0
            for buyer in buyers:
                self.ui.tableWidget.insertRow(row)
                self.ui.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(str(buyer.id)))
                self.ui.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(str(buyer.buyer_name)))
                self.ui.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(str(buyer.phone)))
                self.ui.tableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(str(buyer.buyer_rank)))
                self.ui.tableWidget.setItem(row, 4, QtWidgets.QTableWidgetItem(str(buyer.total_payable)))
                self.ui.tableWidget.setItem(row, 5, QtWidgets.QTableWidgetItem(str(buyer.total_paid)))
                self.ui.tableWidget.setItem(row, 6, QtWidgets.QTableWidgetItem(str(buyer.date)))
                self.ui.tableWidget.setItem(row, 7, QtWidgets.QTableWidgetItem(str(buyer.entry_by)))

                # Add a delete button in the last column
                view_button = QtWidgets.QPushButton("")
                view_icon = QtGui.QIcon("./images/view.png")  # Path to your delete icon
                view_button.setIcon(view_icon)
                view_button.setIconSize(QtCore.QSize(24, 24))  # Set icon size if needed
                view_button.setStyleSheet("background-color: white; border: none;margin-left:50px;")  # Set wh
                view_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                view_button.clicked.connect(lambda _, seller_name=buyer.buyer_name: self.view_profile(seller_name))
                self.ui.tableWidget.setCellWidget(row, 8, view_button)

                delete_button = QtWidgets.QPushButton("")
                delete_icon = QtGui.QIcon("./images/delete.png")  # Path to your delete icon
                delete_button.setIcon(delete_icon)
                delete_button.setIconSize(QtCore.QSize(24, 24))  # Set icon size if needed
                delete_button.setStyleSheet("background-color: white; border: none;margin-left:50px;")  # Set wh
                delete_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                delete_button.clicked.connect(lambda _, r=row: self.delete_row(r))
                self.ui.tableWidget.setCellWidget(row, 9, delete_button)
                row += 1

        except Exception as e:
            QtWidgets.QMessageBox.critical(None, "Buyer Profile Error:", f"An error occurred while filtering data: {e}")

    def delete_row(self, row):
        try:
            reply = QtWidgets.QMessageBox.question(
                None,
                'মুছে ফেলা নিশ্চিত করুন',
                'আপনি কি নিশ্চিত যে আপনি এই প্রোফাইল মুছে ফেলতে চান?',
                QtWidgets.QMessageBox.StandardButton.Yes | QtWidgets.QMessageBox.StandardButton.No,
                QtWidgets.QMessageBox.StandardButton.No
            )

            # If the user confirms, proceed with deletion
            if reply == QtWidgets.QMessageBox.StandardButton.Yes:
                entry_id = self.ui.tableWidget.item(row, 0).text()
                session = self.Session()
                session.query(BuyerProfileModel).filter(BuyerProfileModel.id == entry_id).delete()
                session.commit()
                self.ui.tableWidget.removeRow(row)
        except Exception as ops:
            print(f'error in delete of buyer profile: ({ops})')
        data_save_signals.data_saved.emit()

    def view_profile(self, buyer_name):
        try:
            session = self.Session()
            self.transactions_window = BuyerProfileView(buyer_name, session)
            self.transactions_window.show()
        except Exception as e:
            print(f' err o : {str(e)}')