# Form implementation generated from reading ui file 'pages/cashReportPage.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget
from datetime import datetime, timedelta
from PyQt6.QtCore import Qt, QDate
from models import SellerProfileModel
from features.data_save_signals import data_save_signals
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base
from ui.commissionReportPage_ui import commissionReportPage_ui

class commissionReportPage(QWidget):
    def __init__(self):
        super().__init__()
        self.setup_database()  # First setup database
        self.ui = commissionReportPage_ui()
        self.ui.setupUi(self)
        self.setup_ui()


    def setup_ui(self):
        self.ui.tableWidget.horizontalHeader().setDefaultSectionSize(135)
        self.ui.tableWidget.horizontalHeader().setMinimumSectionSize(135)

        # Set current date ****************
        self.ui.startDateInput.setDisplayFormat("dd/MM/yyyy")
        self.ui.endDateInput.setDisplayFormat("dd/MM/yyyy")
        self.today_date_raw = datetime.now()
        self.today_date = self.today_date_raw.strftime("%d/%m/%Y").lstrip('0').replace('/0', '/')
        self.qdate_today = QDate.fromString(self.today_date, "d/M/yyyy")
        self.ui.startDateInput.setDate(self.qdate_today)
        self.ui.endDateInput.setDate(self.qdate_today)

        data_save_signals.data_saved.connect(self.filter_data)
        self.filter_data()
        self.ui.filterBtn.clicked.connect(self.filter_data)

        # ************ Autocomplete *****************************
        self.ui.sellerFilterInput.textChanged.connect(lambda : self.make_capital(self.ui.sellerFilterInput))

    def setup_database(self):
        from sqlalchemy import create_engine
        from sqlalchemy.orm import sessionmaker, declarative_base

        self.Base = declarative_base()
        self.engine = create_engine('sqlite:///business.db')
        self.Base.metadata.create_all(self.engine)
        self.Session = sessionmaker(bind=self.engine)

    def filter_data(self):
        try:
            start_date = self.ui.startDateInput.date().toPyDate()
            start_date = start_date - timedelta(days=7)
            end_date = self.ui.endDateInput.date().toPyDate()

            # Retrieve data from the database
            session = self.Session()
            query = session.query(SellerProfileModel).filter(SellerProfileModel.date.between(start_date, end_date))
            sellers = query.all()
            # Clear existing table data
            self.ui.tableWidget.clearContents()
            self.ui.tableWidget.setRowCount(0)

            # Populate the table with queried data
            row = 0
            for seller in sellers:
                self.ui.tableWidget.insertRow(row)
                self.ui.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(str(seller.id)))
                self.ui.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(str(seller.seller_name)))
                self.ui.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(str(seller.seller_rank)))
                self.ui.tableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(str(seller.total_commission)))
                self.ui.tableWidget.setItem(row, 4, QtWidgets.QTableWidgetItem(str(seller.date)))
                self.ui.tableWidget.setItem(row, 5, QtWidgets.QTableWidgetItem(str(seller.entry_by)))
                row += 1

        except Exception as e:
            QtWidgets.QMessageBox.critical(None, "Buyer Profile Error:", f"An error occurred while filtering data: {e}")