from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SellerInformation(object):
    def setupUi(self, SellerInformation):
        SellerInformation.setObjectName("SellerInformation")
        SellerInformation.resize(471, 506)
        SellerInformation.setStyleSheet("QLineEdit, QDateEdit{border-radius:10px;\n"
" border:1px solid #B8B8B8;\n"
" padding:2px;}\n"
"QPushButton{background-color:#2D221B;color:white;\n"
"padding:3px 12px 0px 8px;\n"
" border-radius:9px;}")
        self.cancelBtn = QtWidgets.QPushButton(parent=SellerInformation)
        self.cancelBtn.setGeometry(QtCore.QRect(300, 410, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancelBtn.setCheckable(True)
        self.cancelBtn.setObjectName("cancelBtn")
        self.addBtn = QtWidgets.QPushButton(parent=SellerInformation)
        self.addBtn.setGeometry(QtCore.QRect(124, 410, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.addBtn.setFont(font)
        self.addBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.addBtn.setCheckable(True)
        self.addBtn.setObjectName("addBtn")
        self.widget = QtWidgets.QWidget(parent=SellerInformation)
        self.widget.setGeometry(QtCore.QRect(50, 30, 361, 341))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.fishRate = QtWidgets.QLineEdit(parent=self.widget)
        self.fishRate.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.fishRate.setFont(font)
        self.fishRate.setObjectName("fishRate")
        self.gridLayout.addWidget(self.fishRate, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        self.label_5.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setMinimumSize(QtCore.QSize(120, 0))
        self.label_6.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.finalPrice = QtWidgets.QLineEdit(parent=self.widget)
        self.finalPrice.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.finalPrice.setFont(font)
        self.finalPrice.setObjectName("finalPrice")
        self.gridLayout.addWidget(self.finalPrice, 4, 1, 1, 1)
        self.rawPrice = QtWidgets.QLineEdit(parent=self.widget)
        self.rawPrice.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.rawPrice.setFont(font)
        self.rawPrice.setObjectName("rawPrice")
        self.gridLayout.addWidget(self.rawPrice, 3, 1, 1, 1)
        self.fishName = QtWidgets.QLineEdit(parent=self.widget)
        self.fishName.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.fishName.setFont(font)
        self.fishName.setObjectName("fishName")
        self.gridLayout.addWidget(self.fishName, 1, 1, 1, 1)
        self.buyerName = QtWidgets.QLineEdit(parent=self.widget)
        self.buyerName.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.buyerName.setFont(font)
        self.buyerName.setObjectName("buyerName")
        self.gridLayout.addWidget(self.buyerName, 0, 1, 1, 1)
        self.totalPrice = QtWidgets.QLineEdit(parent=self.widget)
        self.totalPrice.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.totalPrice.setFont(font)
        self.totalPrice.setObjectName("totalPrice")
        self.gridLayout.addWidget(self.totalPrice, 5, 1, 1, 1)

        self.retranslateUi(SellerInformation)
        QtCore.QMetaObject.connectSlotsByName(SellerInformation)

    def retranslateUi(self, SellerInformation):
        _translate = QtCore.QCoreApplication.translate
        SellerInformation.setWindowTitle(_translate("SellerInformation", "ক্রেতার তথ্য"))
        self.cancelBtn.setText(_translate("SellerInformation", "বাতিল "))
        self.addBtn.setText(_translate("SellerInformation", "ঠিক আছে"))
        self.label_2.setText(_translate("SellerInformation", "মাছের নাম : "))
        self.label_4.setText(_translate("SellerInformation", "কাঁচা : "))
        self.label.setText(_translate("SellerInformation", "ক্রেতার নাম : "))
        self.label_5.setText(_translate("SellerInformation", "পাকা : "))
        self.label_6.setText(_translate("SellerInformation", "মোট দাম :"))
        self.label_3.setText(_translate("SellerInformation", "মাছের দর : "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SellerInformation = QtWidgets.QDialog()
    ui = Ui_SellerInformation()
    ui.setupUi(SellerInformation)
    SellerInformation.show()
    sys.exit(app.exec())
