from PyQt6 import QtCore, QtGui, QtWidgets
from models import *
from features.data_save_signals import data_save_signals


class Ui_LoanPage(object):
    def setupUi(self, costExpenseMain):

        # ****************** Declear database ************************
        self.Base = declarative_base()
        self.engine = create_engine('sqlite:///business.db')    # change db url
        self.Base.metadata.create_all(self.engine)
        self.Session = sessionmaker(bind=self.engine)
        # ******************* end db ***************************

        costExpenseMain.setObjectName("costExpenseMain")
        costExpenseMain.resize(944, 650)
        costExpenseMain.setStyleSheet("""*{text-align: left;}
                                      QLineEdit, QComboBox{border-radius:10px;
                                                           border:1px solid #B8B8B8;
                                                           padding:2px;}
                                      QPushButton{background-color:#150E0A;
                                                  color:white;
                                                  padding:3px 12px 0px 8px;
                                                  border-radius:9px;
                                                  text-align:center;}
                                      QDateEdit{border:1px solid #B8B8B8;border-radius:5px;}
                                      QDateEdit::drop-down {
                                            image: url('./images/down-arrow.png');
                                            margin:3px 4px 0 0;
                                            border:1px solid #DEDEDE;
                                           }
                                      """)
        self.verticalLayout = QtWidgets.QVBoxLayout(costExpenseMain)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout.setObjectName("verticalLayout")
        # self.costExpenseHeader = QtWidgets.QWidget(parent=costExpenseMain)
        # self.costExpenseHeader.setMinimumSize(QtCore.QSize(0, 60))
        # self.costExpenseHeader.setMaximumSize(QtCore.QSize(16777215, 80))
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # self.costExpenseHeader.setFont(font)
        # self.costExpenseHeader.setObjectName("costExpenseHeader")
        # self.costExpenseHeader_Layout = QtWidgets.QHBoxLayout(self.costExpenseHeader)
        # self.costExpenseHeader_Layout.setContentsMargins(0, 0, 0, 0)
        # self.costExpenseHeader_Layout.setSpacing(0)
        # self.costExpenseHeader_Layout.setObjectName("costExpenseHeader_Layout")
        # self.accountNameFrame = QtWidgets.QFrame(parent=self.costExpenseHeader)
        # self.accountNameFrame.setMinimumSize(QtCore.QSize(0, 0))
        # self.accountNameFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # self.accountNameFrame.setFont(font)
        # self.accountNameFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        # self.accountNameFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        # self.accountNameFrame.setObjectName("accountNameFrame")
        # self.accountNameFrame_layout = QtWidgets.QVBoxLayout(self.accountNameFrame)
        # self.accountNameFrame_layout.setContentsMargins(0, 0, 10, 0)
        # self.accountNameFrame_layout.setSpacing(0)
        # self.accountNameFrame_layout.setObjectName("accountNameFrame_layout")
        # self.accountNameLabel = QtWidgets.QLabel(parent=self.accountNameFrame)
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(12)
        # self.accountNameLabel.setFont(font)
        # self.accountNameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        # self.accountNameLabel.setObjectName("accountNameLabel")
        # self.accountNameFrame_layout.addWidget(self.accountNameLabel)
        # self.accountNameSelect = QtWidgets.QComboBox(parent=self.accountNameFrame)
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(12)
        # self.accountNameSelect.setFont(font)
        # self.accountNameSelect.setObjectName("accountNameSelect")
        # self.accountNameSelect.addItem("")
        # self.accountNameSelect.addItem("")
        # self.accountNameSelect.addItem("")
        # self.accountNameSelect.addItem("")
        # self.accountNameSelect.addItem("")
        # self.accountNameSelect.addItem("")
        # self.accountNameSelect.addItem("")
        # self.accountNameSelect.addItem("")
        # self.accountNameSelect.addItem("")
        # self.accountNameFrame_layout.addWidget(self.accountNameSelect)
        # self.costExpenseHeader_Layout.addWidget(self.accountNameFrame)
        # self.startDateFrame = QtWidgets.QFrame(parent=self.costExpenseHeader)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.startDateFrame.sizePolicy().hasHeightForWidth())
        # self.startDateFrame.setSizePolicy(sizePolicy)
        # self.startDateFrame.setMinimumSize(QtCore.QSize(0, 0))
        # self.startDateFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # self.startDateFrame.setFont(font)
        # self.startDateFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        # self.startDateFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        # self.startDateFrame.setObjectName("startDateFrame")
        # self.startDateFrame_Layout = QtWidgets.QVBoxLayout(self.startDateFrame)
        # self.startDateFrame_Layout.setContentsMargins(10, 0, 10, 0)
        # self.startDateFrame_Layout.setSpacing(0)
        # self.startDateFrame_Layout.setObjectName("startDateFrame_Layout")
        # self.startDateLabel = QtWidgets.QLabel(parent=self.startDateFrame)
        # self.startDateLabel.setMinimumSize(QtCore.QSize(0, 0))
        # self.startDateLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(12)
        # self.startDateLabel.setFont(font)
        # self.startDateLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        # self.startDateLabel.setObjectName("startDateLabel")
        # self.startDateFrame_Layout.addWidget(self.startDateLabel)
        # self.startDateInput = QtWidgets.QDateEdit(parent=self.startDateFrame)
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(12)
        # self.startDateInput.setFont(font)
        # self.startDateInput.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        # self.startDateInput.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        # self.startDateInput.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        # self.startDateInput.setCalendarPopup(True)
        # self.startDateInput.setObjectName("startDateInput")
        # self.startDateFrame_Layout.addWidget(self.startDateInput)
        # self.costExpenseHeader_Layout.addWidget(self.startDateFrame)
        # self.endDateFrame = QtWidgets.QFrame(parent=self.costExpenseHeader)
        # self.endDateFrame.setMinimumSize(QtCore.QSize(0, 0))
        # self.endDateFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # self.endDateFrame.setFont(font)
        # self.endDateFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        # self.endDateFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        # self.endDateFrame.setObjectName("endDateFrame")
        # self.endDateFrame_Layout = QtWidgets.QVBoxLayout(self.endDateFrame)
        # self.endDateFrame_Layout.setContentsMargins(10, 0, 10, 0)
        # self.endDateFrame_Layout.setSpacing(0)
        # self.endDateFrame_Layout.setObjectName("endDateFrame_Layout")
        # self.endDateLabel = QtWidgets.QLabel(parent=self.endDateFrame)
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(12)
        # self.endDateLabel.setFont(font)
        # self.endDateLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        # self.endDateLabel.setObjectName("endDateLabel")
        # self.endDateFrame_Layout.addWidget(self.endDateLabel)
        # self.endDateInput = QtWidgets.QDateEdit(parent=self.endDateFrame)
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(12)
        # self.endDateInput.setFont(font)
        # self.endDateInput.setCalendarPopup(True)
        # self.endDateInput.setDate(QtCore.QDate(2025, 1, 1))
        # self.endDateInput.setObjectName("endDateInput")
        # self.endDateFrame_Layout.addWidget(self.endDateInput)
        # self.costExpenseHeader_Layout.addWidget(self.endDateFrame)
        # self.filterActionFrame = QtWidgets.QFrame(parent=self.costExpenseHeader)
        # self.filterActionFrame.setMinimumSize(QtCore.QSize(0, 0))
        # self.filterActionFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # self.filterActionFrame.setFont(font)
        # self.filterActionFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        # self.filterActionFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        # self.filterActionFrame.setObjectName("filterActionFrame")
        # self.filterActionFrame_Layout = QtWidgets.QVBoxLayout(self.filterActionFrame)
        # self.filterActionFrame_Layout.setContentsMargins(10, 0, 10, 0)
        # self.filterActionFrame_Layout.setSpacing(0)
        # self.filterActionFrame_Layout.setObjectName("filterActionFrame_Layout")
        # self.filterLabel = QtWidgets.QLabel(parent=self.filterActionFrame)
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(12)
        # self.filterLabel.setFont(font)
        # self.filterLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        # self.filterLabel.setObjectName("filterLabel")
        # self.filterActionFrame_Layout.addWidget(self.filterLabel)
        # self.filterBtn = QtWidgets.QPushButton(parent=self.filterActionFrame)
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(12)
        # self.filterBtn.setFont(font)
        # self.filterBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        # self.filterBtn.setStyleSheet("")
        # icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap("./icons/filter.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        # self.filterBtn.setIcon(icon)
        # self.filterBtn.setObjectName("filterBtn")
        # self.filterActionFrame_Layout.addWidget(self.filterBtn)
        # self.costExpenseHeader_Layout.addWidget(self.filterActionFrame)
        # self.costExpenseEntryframe = QtWidgets.QFrame(parent=self.costExpenseHeader)
        # self.costExpenseEntryframe.setMinimumSize(QtCore.QSize(0, 0))
        # self.costExpenseEntryframe.setMaximumSize(QtCore.QSize(16777215, 16777215))
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # self.costExpenseEntryframe.setFont(font)
        # self.costExpenseEntryframe.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        # self.costExpenseEntryframe.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        # self.costExpenseEntryframe.setObjectName("costExpenseEntryframe")
        # self.costExpenseEntryframe_Layout = QtWidgets.QVBoxLayout(self.costExpenseEntryframe)
        # self.costExpenseEntryframe_Layout.setContentsMargins(10, 0, 0, 0)
        # self.costExpenseEntryframe_Layout.setSpacing(0)
        # self.costExpenseEntryframe_Layout.setObjectName("costExpenseEntryframe_Layout")
        # self.costExpenseEntryLabel = QtWidgets.QLabel(parent=self.costExpenseEntryframe)
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(12)
        # self.costExpenseEntryLabel.setFont(font)
        # self.costExpenseEntryLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        # self.costExpenseEntryLabel.setObjectName("costExpenseEntryLabel")
        # self.costExpenseEntryframe_Layout.addWidget(self.costExpenseEntryLabel)
        # self.costExpenseEntryBtn = QtWidgets.QPushButton(parent=self.costExpenseEntryframe)
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(12)
        # self.costExpenseEntryBtn.setFont(font)
        # self.costExpenseEntryBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        # self.costExpenseEntryBtn.setStyleSheet("")
        # icon1 = QtGui.QIcon()
        # icon1.addPixmap(QtGui.QPixmap("./icons/edit-3.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        # self.costExpenseEntryBtn.setIcon(icon1)
        # self.costExpenseEntryBtn.setObjectName("costExpenseEntryBtn")
        # self.costExpenseEntryframe_Layout.addWidget(self.costExpenseEntryBtn)
        # self.costExpenseHeader_Layout.addWidget(self.costExpenseEntryframe)
        # self.verticalLayout.addWidget(self.costExpenseHeader)
        self.costExpenseBody = QtWidgets.QWidget(parent=costExpenseMain)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.costExpenseBody.setFont(font)
        self.costExpenseBody.setObjectName("costExpenseBody")
        self.cashReportBody_Layout = QtWidgets.QHBoxLayout(self.costExpenseBody)
        self.cashReportBody_Layout.setContentsMargins(0, 10, 0, 0)
        self.cashReportBody_Layout.setSpacing(0)
        self.cashReportBody_Layout.setObjectName("cashReportBody_Layout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.costExpenseBody)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("""QHeaderView::section, QHeaderView{background-color: #2D221B;
                                                                            color: white;
                                                                            font-size: 12pt;
                                                                            text-align: center;
                                                                            }""")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tableWidget.setFont(font)
        font.setPointSize(12)  # Set the font size to 12 points
        self.tableWidget.setFont(font)
        self.cashReportBody_Layout.addWidget(self.tableWidget)
        self.verticalLayout.addWidget(self.costExpenseBody)
        self.costExpenseBottom = QtWidgets.QWidget(parent=costExpenseMain)
        self.costExpenseBottom.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.costExpenseBottom.setFont(font)
        self.costExpenseBottom.setStyleSheet("""#paidAmount, #receivedAmount, #revenueAmount{background:white;
                                                                                            color:black;
                                                                                            border-radius:10px;
                                                                                            border:1px solid #828282;
                                                                                            }
                                                                                            """)
        self.costExpenseBottom.setObjectName("costExpenseBottom")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.costExpenseBottom)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.retranslateUi(costExpenseMain)
        QtCore.QMetaObject.connectSlotsByName(costExpenseMain)



    def retranslateUi(self, costExpenseMain):
        _translate = QtCore.QCoreApplication.translate
        costExpenseMain.setWindowTitle(_translate("costExpenseMain", "ঋণ এর হিসাব"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("costExpenseMain", "তারিখ "))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("costExpenseMain", "হিসাবের নাম"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("costExpenseMain", "প্রদান কারীর নাম"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("costExpenseMain", "পরিমান"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("costExpenseMain", "এন্ট্রি বাই"))

        self.tableWidget.horizontalHeader().setDefaultSectionSize(240)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(240)
        self.tableWidget.verticalHeader().setVisible(False)
        self.filter_data()
        data_save_signals.data_saved.connect(self.filter_data)

    def filter_data(self):
        try:
            # Retrieve data from the database
            session = self.Session()
            query = session.query(LoanModel).filter(LoanModel.amount > 0)
            all_entries = query.all()
            # Clear existing table data
            self.tableWidget.clearContents()
            self.tableWidget.setRowCount(0)
            # Populate the table with queried data
            row = 0
            for entry in all_entries:
                self.tableWidget.insertRow(row)
                self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(str(entry.date)))
                self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem("ঋণ গ্রহণ"))
                self.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(str(entry.loan_payer_name)))
                self.tableWidget.setItem(row, 3, QtWidgets.QTableWidgetItem(str(entry.amount)))
                self.tableWidget.setItem(row, 4, QtWidgets.QTableWidgetItem(str(entry.entry_by)))

                row += 1
        except Exception as e:
            QtWidgets.QMessageBox.critical(None, "seller Profile Error", f"An error occurred while filtering data: {e}")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    costExpenseMain = QtWidgets.QWidget()
    ui = Ui_LoanPage()
    ui.setupUi(costExpenseMain)
    costExpenseMain.show()
    sys.exit(app.exec())
