# Form implementation generated from reading ui file 'UI/settings.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from models import *
from sqlalchemy.exc import SQLAlchemyError
from features.data_save_signals import data_save_signals

class Ui_settingsPage(object):
    def setupUi(self, settingsPage):


        # ****************** Declear database ************************
        self.Base = declarative_base()
        self.engine = create_engine('sqlite:///business.db')    # change db url
        self.Base.metadata.create_all(self.engine)
        self.Session = sessionmaker(bind=self.engine)
        # ******************* end db ***************************

        settingsPage.setObjectName("settingsPage")
        settingsPage.resize(964, 623)
        settingsPage.setStyleSheet("*{\n"
"  text-align: left;\n"
"}\n"
"QLineEdit, QDateEdit{\n"
"border-radius:10px;\n"
"border:1px solid #B8B8B8;\n"
"padding:2px;\n"
"}\n"
"QPushButton{\n"
"background-color:#2D221B;\n"
"color:white;\n"
"padding:5px 8px;\n"
"border-radius:9px;\n"
"}")
        self.label = QtWidgets.QLabel(parent=settingsPage)
        self.label.setGeometry(QtCore.QRect(60, 40, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.updateBtn = QtWidgets.QPushButton(parent=settingsPage)
        self.updateBtn.setGeometry(QtCore.QRect(60, 330, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.updateBtn.setFont(font)
        self.updateBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.updateBtn.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(parent=settingsPage)
        self.widget.setGeometry(QtCore.QRect(60, 130, 508, 37))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.username = QtWidgets.QLineEdit(parent=self.widget)
        self.username.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.username.setFont(font)
        self.username.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.username)
        self.widget1 = QtWidgets.QWidget(parent=settingsPage)
        self.widget1.setGeometry(QtCore.QRect(60, 200, 508, 37))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget1)
        self.label_3.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.commision = QtWidgets.QLineEdit(parent=self.widget1)
        self.commision.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.commision.setFont(font)
        self.commision.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.commision)
        self.widget2 = QtWidgets.QWidget(parent=settingsPage)
        self.widget2.setGeometry(QtCore.QRect(60, 270, 508, 37))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.widget2)
        self.label_4.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.dhol = QtWidgets.QLineEdit(parent=self.widget2)
        self.dhol.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.dhol.setFont(font)
        self.dhol.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.dhol)

        self.retranslateUi(settingsPage)
        QtCore.QMetaObject.connectSlotsByName(settingsPage)

    def retranslateUi(self, settingsPage):
        _translate = QtCore.QCoreApplication.translate
        settingsPage.setWindowTitle(_translate("settingsPage", "Form"))
        self.label.setText(_translate("settingsPage", "সেটিংস "))
        self.updateBtn.setText(_translate("settingsPage", "আপডেট "))
        self.label_2.setText(_translate("settingsPage", "এন্ট্রি বাই ইউজারনেম :"))
        self.label_3.setText(_translate("settingsPage", "কমিশন (শতাংশ) :"))
        self.label_4.setText(_translate("settingsPage", "ঢল (গ্রাম) :"))
        session = self.Session()
        setting = session.query(SettingModel).first()
        self.username.setText(setting.username)
        self.commision.setText(str(setting.commission))
        self.dhol.setText(str(setting.dhol))
        session.close()
        self.updateBtn.clicked.connect(self.update_setting)

    def retranslateUi(self, settingsPage):
        _translate = QtCore.QCoreApplication.translate
        settingsPage.setWindowTitle(_translate("settingsPage", "Form"))
        self.label.setText(_translate("settingsPage", "সেটিংস "))
        self.updateBtn.setText(_translate("settingsPage", "আপডেট "))
        self.label_2.setText(_translate("settingsPage", "এন্ট্রি বাই ইউজারনেম :"))
        self.label_3.setText(_translate("settingsPage", "কমিশন (শতাংশ) :"))
        self.label_4.setText(_translate("settingsPage", "ঢলক (গ্রাম) :"))

        session = self.Session()
        try:
            setting = session.query(SettingModel).first()
            if setting:
                self.username.setText(setting.username)
                self.commision.setText(str(setting.commission))
                self.dhol.setText(str(setting.dhol))
            else:
                QtWidgets.QMessageBox.warning(None, "Error", f"সেটিংস পাওয়া যায়নি")
        except SQLAlchemyError as e:
            QtWidgets.QMessageBox.warning(None, "Error", f"ডেটাবেস ত্রুটি: {e}")
        finally:
            session.close()

        self.updateBtn.clicked.connect(self.update_setting)

    def update_setting(self):
        username = self.username.text().strip()
        commision = self.commision.text().strip()
        dhol = self.dhol.text().strip()

        # Check if any field is empty
        if not username or not commision or not dhol:
            QtWidgets.QMessageBox.warning(None, "Error", f"কোন ফিল্ড ফাঁকা থাকা যাবেনা")
            return

        # Validate commission
        try:
            commission_value = float(commision)
        except ValueError:
            QtWidgets.QMessageBox.warning(None, "Error", f"কমিশন (শতাংশ) একটি সঠিক সংখ্যা প্রদান করুন")
            return

        # Validate dhol
        try:
            dhol_value = int(dhol)
        except ValueError:
            QtWidgets.QMessageBox.warning(None, "Error", f"ঢল (গ্রাম) একটি সঠিক সংখ্যা প্রদান করুন")
            return

        # Update the setting
        Session = sessionmaker(bind=self.engine)
        session = Session()
        try:
            setting = session.query(SettingModel).first()
            if setting is None:
                QtWidgets.QMessageBox.warning(None, "Error", f"কোনো সেটিংস পাওয়া যায়নি")
                return

            setting.username = username
            setting.commission = commission_value
            setting.dhol = dhol_value
            session.commit()
        except SQLAlchemyError as e:
            QtWidgets.QMessageBox.warning(None, "Error", f"সেটিংস আপডেট করতে সমস্যা হয়েছে: {e}")
            session.rollback()
        finally:
            session.close()
        QtWidgets.QMessageBox.information(None, "Success", f"সেটিংস আপডেট হয়েছে")
        data_save_signals.data_saved.emit()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    settingsPage = QtWidgets.QWidget()
    ui = Ui_settingsPage()
    ui.setupUi(settingsPage)
    settingsPage.show()
    sys.exit(app.exec())
