# Form implementation generated from reading ui file 'pages/cashReportPage.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget
from datetime import datetime, timedelta
from PyQt6.QtCore import Qt, QDate
from features.data_save_signals import data_save_signals
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base
from ui.usersPage_ui import Ui_usersPage
from models import *

class userPage(QWidget):
    def __init__(self):
        super().__init__()
        self.setup_database()  # First setup database
        self.ui = Ui_usersPage()
        self.ui.setupUi(self)
        self.setup_ui()


    def setup_ui(self):
        self.ui.tableWidget.horizontalHeader().setDefaultSectionSize(180)
        self.ui.tableWidget.horizontalHeader().setMinimumSectionSize(180)

        data_save_signals.data_saved.connect(self.filter_data)
        self.filter_data()

    def setup_database(self):
        from sqlalchemy import create_engine
        from sqlalchemy.orm import sessionmaker, declarative_base

        self.Base = declarative_base()
        self.engine = create_engine('sqlite:///business.db')
        self.Base.metadata.create_all(self.engine)
        self.Session = sessionmaker(bind=self.engine)


    def filter_data(self):
        try:
            session = self.Session()
            users = session.query(UserModel).all()
            # Clear existing table data
            self.ui.tableWidget.clearContents()
            self.ui.tableWidget.setRowCount(0)

            # Populate the table with queried data
            row = 0
            for user in users:
                self.ui.tableWidget.insertRow(row)
                self.ui.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(str(user.id)))
                self.ui.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(str(user.username)))
                self.ui.tableWidget.setItem(row, 2, QtWidgets.QTableWidgetItem(str(user.role)))

                # Add a delete button in the last column
                edit_button = QtWidgets.QPushButton("")
                edit_icon = QtGui.QIcon("./images/view.png")  # Path to your delete icon
                edit_button.setIcon(edit_icon)
                edit_button.setIconSize(QtCore.QSize(24, 24))  # Set icon size if needed
                edit_button.setStyleSheet("background-color: white; border: none;margin-left:50px;")  # Set wh
                edit_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                edit_button.clicked.connect(lambda _, username=user.username: self.edit_profile(username))
                self.ui.tableWidget.setCellWidget(row, 3, edit_button)

                delete_button = QtWidgets.QPushButton("")
                delete_icon = QtGui.QIcon("./images/delete.png")  # Path to your delete icon
                delete_button.setIcon(delete_icon)
                delete_button.setIconSize(QtCore.QSize(24, 24))  # Set icon size if needed
                delete_button.setStyleSheet("background-color: white; border: none;margin-left:50px;")  # Set wh
                delete_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                delete_button.clicked.connect(lambda _, r=row: self.delete_row(r))
                self.ui.tableWidget.setCellWidget(row, 4, delete_button)
                row += 1

        except Exception as e:
            QtWidgets.QMessageBox.critical(None, "Users Profile Error:", f"An error occurred while filtering data: {e}")

    def delete_row(self, row):
        try:
            reply = QtWidgets.QMessageBox.question(
                None,
                'মুছে ফেলা নিশ্চিত করুন',
                'আপনি কি নিশ্চিত যে আপনি এই প্রোফাইল মুছে ফেলতে চান?',
                QtWidgets.QMessageBox.StandardButton.Yes | QtWidgets.QMessageBox.StandardButton.No,
                QtWidgets.QMessageBox.StandardButton.No
            )

            # If the user confirms, proceed with deletion
            if reply == QtWidgets.QMessageBox.StandardButton.Yes:
                entry_id = self.ui.tableWidget.item(row, 0).text()
                session = self.Session()
                session.commit()
                self.ui.tableWidget.removeRow(row)
        except Exception as ops:
            print(f'error in delete of buyer profile: ({ops})')
        data_save_signals.data_saved.emit()

    def edit_profile(self, buyer_name):
        try:
            session = self.Session()
            self.transactions_window = ProfileEditForm(buyer_name, session)
            self.transactions_window.show()
        except Exception as e:
            print(f' err o : {str(e)}')