# Form implementation generated from reading ui file 'ui_files/profile_edit.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProfileEdit(object):
    def setupUi(self, ProfileEdit):
        ProfileEdit.setObjectName("ProfileEdit")
        ProfileEdit.resize(387, 370)
        ProfileEdit.setStyleSheet("QLineEdit, QDateEdit{ border-radius:10px;\n"
"border:1px solid #B8B8B8;\n"
" padding:3px;}\n"
"QPushButton{background-color:#2D221B;\n"
"                                        color:white;\n"
"                                        padding:5px 12px;\n"
"                                        border-radius:9px;}\n"
" QComboBox{border-radius:10px;background:#E1E1E1;border:1px solid #B8B8B8; padding:3px;}")
        self.widget = QtWidgets.QWidget(parent=ProfileEdit)
        self.widget.setGeometry(QtCore.QRect(40, 30, 311, 221))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(parent=self.widget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.phone = QtWidgets.QLineEdit(parent=self.widget)
        self.phone.setObjectName("phone")
        self.gridLayout.addWidget(self.phone, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.address = QtWidgets.QLineEdit(parent=self.widget)
        self.address.setObjectName("address")
        self.gridLayout.addWidget(self.address, 2, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(parent=ProfileEdit)
        self.widget1.setGeometry(QtCore.QRect(100, 290, 251, 38))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cancel = QtWidgets.QPushButton(parent=self.widget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cancel.setFont(font)
        self.cancel.setObjectName("cancel")
        self.gridLayout_2.addWidget(self.cancel, 0, 0, 1, 1)
        self.update = QtWidgets.QPushButton(parent=self.widget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.update.setFont(font)
        self.update.setObjectName("update")
        self.gridLayout_2.addWidget(self.update, 0, 1, 1, 1)

        self.retranslateUi(ProfileEdit)
        QtCore.QMetaObject.connectSlotsByName(ProfileEdit)

    def retranslateUi(self, ProfileEdit):
        _translate = QtCore.QCoreApplication.translate
        ProfileEdit.setWindowTitle(_translate("ProfileEdit", "Dialog"))
        self.label.setText(_translate("ProfileEdit", "নাম :"))
        self.label_2.setText(_translate("ProfileEdit", "ফোন : "))
        self.label_3.setText(_translate("ProfileEdit", "ঠিকানা : "))
        self.cancel.setText(_translate("ProfileEdit", "বাতিল করুন"))
        self.update.setText(_translate("ProfileEdit", "আপডেট"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProfileEdit = QtWidgets.QDialog()
    ui = Ui_ProfileEdit()
    ui.setupUi(ProfileEdit)
    ProfileEdit.show()
    sys.exit(app.exec())
