# Form implementation generated from reading ui file 'ui_files/settings.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_settingsPage(object):
    def setupUi(self, settingsPage):
        settingsPage.setObjectName("settingsPage")
        settingsPage.resize(964, 623)
        settingsPage.setStyleSheet("*{\n"
"  text-align: left;\n"
"}\n"
"QLineEdit, QDateEdit{\n"
"border-radius:10px;\n"
"border:1px solid #B8B8B8;\n"
"padding:2px;\n"
"}\n"
"QPushButton{\n"
"background-color:#2D221B;\n"
"color:white;\n"
"padding:5px 8px;\n"
"border-radius:9px;\n"
"}")
        self.label = QtWidgets.QLabel(parent=settingsPage)
        self.label.setGeometry(QtCore.QRect(60, 40, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.updateBtn = QtWidgets.QPushButton(parent=settingsPage)
        self.updateBtn.setGeometry(QtCore.QRect(60, 380, 111, 51))
        font = QtGui.QFont()
        font.setFamily("SutonnyMJ")
        font.setPointSize(18)
        self.updateBtn.setFont(font)
        self.updateBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.updateBtn.setObjectName("updateBtn")
        self.layoutWidget = QtWidgets.QWidget(parent=settingsPage)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 130, 501, 37))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("SutonnyMJ")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.username = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.username.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.username.setFont(font)
        self.username.setObjectName("username")
        self.horizontalLayout.addWidget(self.username)
        self.layoutWidget1 = QtWidgets.QWidget(parent=settingsPage)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 260, 501, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_3.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("SutonnyMJ")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.commission = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.commission.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.commission.setFont(font)
        self.commission.setObjectName("commission")
        self.horizontalLayout_2.addWidget(self.commission)
        self.layoutWidget2 = QtWidgets.QWidget(parent=settingsPage)
        self.layoutWidget2.setGeometry(QtCore.QRect(60, 320, 501, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.label_4.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("SutonnyMJ")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.dhol = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.dhol.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.dhol.setFont(font)
        self.dhol.setObjectName("dhol")
        self.horizontalLayout_3.addWidget(self.dhol)
        self.viewPassword = QtWidgets.QPushButton(parent=settingsPage)
        self.viewPassword.setGeometry(QtCore.QRect(580, 190, 41, 35))
        self.viewPassword.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.viewPassword.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.viewPassword.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/view.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.viewPassword.setIcon(icon)
        self.viewPassword.setIconSize(QtCore.QSize(25, 25))
        self.viewPassword.setCheckable(True)
        self.viewPassword.setAutoExclusive(True)
        self.viewPassword.setObjectName("viewPassword")
        self.label_5 = QtWidgets.QLabel(parent=settingsPage)
        self.label_5.setGeometry(QtCore.QRect(62, 191, 200, 32))
        self.label_5.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("SutonnyMJ")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.password = QtWidgets.QLineEdit(parent=settingsPage)
        self.password.setGeometry(QtCore.QRect(268, 191, 291, 37))
        self.password.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.password.setFont(font)
        self.password.setObjectName("password")

        self.retranslateUi(settingsPage)
        QtCore.QMetaObject.connectSlotsByName(settingsPage)

    def retranslateUi(self, settingsPage):
        _translate = QtCore.QCoreApplication.translate
        settingsPage.setWindowTitle(_translate("settingsPage", "Form"))
        self.label.setText(_translate("settingsPage", "সেটিংস "))
        self.updateBtn.setText(_translate("settingsPage", "আপডেট "))
        self.label_2.setText(_translate("settingsPage", "ইউজারনেম :"))
        self.label_3.setText(_translate("settingsPage", "কমিশন (শতাংশ) :"))
        self.label_4.setText(_translate("settingsPage", "ঢল (গ্রাম) :"))
        self.label_5.setText(_translate("settingsPage", "পাসওয়ার্ড :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    settingsPage = QtWidgets.QWidget()
    ui = Ui_settingsPage()
    ui.setupUi(settingsPage)
    settingsPage.show()
    sys.exit(app.exec())
