# Form implementation generated from reading ui file 'ui_files/usersPage.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_usersPage(object):
    def setupUi(self, usersPage):
        usersPage.setObjectName("usersPage")
        usersPage.resize(755, 575)
        usersPage.setMinimumSize(QtCore.QSize(300, 0))
        usersPage.setStyleSheet("*{\n"
"  text-align: left;\n"
"}\n"
"QLineEdit{\n"
"border-radius:10px;\n"
"border:1px solid #B8B8B8;\n"
"padding:2px;\n"
"}\n"
"QPushButton{\n"
"background-color:#150E0A;\n"
"color:white;\n"
"padding:3px 12px 0px 8px;\n"
"border-radius:9px;\n"
"text-align:center;\n"
"}\n"
"QDateEdit{\n"
"border:1px solid #B8B8B8;\n"
"border-radius:5px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(usersPage)
        self.verticalLayout.setContentsMargins(50, 20, 50, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=usersPage)
        font = QtGui.QFont()
        font.setFamily("SutonnyMJ")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.addUser = QtWidgets.QPushButton(parent=usersPage)
        self.addUser.setMinimumSize(QtCore.QSize(160, 35))
        self.addUser.setMaximumSize(QtCore.QSize(160, 35))
        font = QtGui.QFont()
        font.setFamily("SutonnyMJ")
        font.setPointSize(12)
        self.addUser.setFont(font)
        self.addUser.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icons/user-plus.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addUser.setIcon(icon)
        self.addUser.setIconSize(QtCore.QSize(25, 25))
        self.addUser.setObjectName("addUser")
        self.verticalLayout.addWidget(self.addUser)
        self.usersBody = QtWidgets.QWidget(parent=usersPage)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.usersBody.setFont(font)
        self.usersBody.setObjectName("usersBody")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.usersBody)
        self.horizontalLayout.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.usersBody)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QHeaderView::section, QHeaderView{\n"
"    background-color: #2D221B;\n"
"    color: white;   \n"
"    font-size: 12pt;  \n"
"    text-align: center; \n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("SutonnyMJ")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("SutonnyMJ")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("SutonnyMJ")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("SutonnyMJ")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("SutonnyMJ")
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(120)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.verticalLayout.addWidget(self.usersBody)

        self.retranslateUi(usersPage)
        QtCore.QMetaObject.connectSlotsByName(usersPage)

    def retranslateUi(self, usersPage):
        _translate = QtCore.QCoreApplication.translate
        usersPage.setWindowTitle(_translate("usersPage", "Form"))
        self.label.setText(_translate("usersPage", "ইউজার পেজ"))
        self.addUser.setText(_translate("usersPage", "অ্যাড ইউজার"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("usersPage", "আইডি"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("usersPage", "ইউজারনেম"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("usersPage", "রোল"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("usersPage", "এডিট"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("usersPage", "ডিলিট"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    usersPage = QtWidgets.QWidget()
    ui = Ui_usersPage()
    ui.setupUi(usersPage)
    usersPage.show()
    sys.exit(app.exec())
