# Form implementation generated from reading ui file 'UI/add_buyer_form.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
from PyQt6.QtGui import QIcon
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base
from features.data_save_signals import data_save_signals
from models import BuyerProfileModel, SettingModel
from datetime import datetime
import sys

# from pathlib import Path
# sys.path.append(str(Path(__file__).resolve().parent.parent))

class Ui_AddBuyer(object):
    def setupUi(self, AddBuyer, username):

        # ****************** Declear database ************************
        self.Base = declarative_base()
        self.engine = create_engine('sqlite:///business.db')    # change db url
        self.Base.metadata.create_all(self.engine)
        self.Session = sessionmaker(bind=self.engine)
        # ******************* end db ***************************


        AddBuyer.setObjectName("SellerInformation")
        AddBuyer.resize(491, 497)
        AddBuyer.setWindowIcon(QIcon("images/logo.png"))
        AddBuyer.setStyleSheet("""QLineEdit, QDateEdit{ border-radius:10px;
                                                        border:1px solid #B8B8B8;
                                                        padding:3px;}
                                  QPushButton{background-color:#2D221B;
                                             color:white;
                                             padding:5px 12px;
                                             border-radius:9px;}
                                QComboBox{border-radius:10px;
                                          background:#E1E1E1;
                                          border:1px solid #B8B8B8;
                                          padding:3px;}
                                          """)
        self.widget = QtWidgets.QWidget(parent=AddBuyer)
        self.widget.setGeometry(QtCore.QRect(62, 22, 361, 391))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.buyerName = QtWidgets.QLineEdit(parent=self.widget)
        self.buyerName.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.buyerName.setFont(font)
        self.buyerName.setObjectName("buyerName")
        self.gridLayout.addWidget(self.buyerName, 0, 1, 1, 1)

        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.mobile = QtWidgets.QLineEdit(parent=self.widget)
        self.mobile.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.mobile.setFont(font)
        self.mobile.setObjectName("mobile")
        self.gridLayout.addWidget(self.mobile, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.fishName = QtWidgets.QLineEdit(parent=self.widget)
        self.fishName.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.fishName.setFont(font)
        self.fishName.setObjectName("fishName")
        self.gridLayout.addWidget(self.fishName, 2, 1, 1, 1)
        self.weightType = QtWidgets.QComboBox(parent=self.widget)
        self.weightType.setEnabled(True)
        self.weightType.setMinimumSize(QtCore.QSize(210, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.weightType.setFont(font)
        self.weightType.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.weightType.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.weightType.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.weightType.setAutoFillBackground(False)
        self.weightType.setStyleSheet("")
        self.weightType.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.weightType.setIconSize(QtCore.QSize(24, 24))
        self.weightType.setFrame(True)
        self.weightType.setObjectName("weightType")
        self.weightType.addItem("")
        self.weightType.addItem("")
        self.weightType.addItem("")
        self.gridLayout.addWidget(self.weightType, 3, 1, 1, 1)
        self.fishRate = QtWidgets.QLineEdit(parent=self.widget)
        self.fishRate.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.fishRate.setFont(font)
        self.fishRate.setObjectName("fishRate")
        self.gridLayout.addWidget(self.fishRate, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.rawWeight = QtWidgets.QLineEdit(parent=self.widget)
        self.rawWeight.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.rawWeight.setFont(font)
        self.rawWeight.setObjectName("rawWeight")
        self.gridLayout.addWidget(self.rawWeight, 5, 1, 1, 1)
        self.finalWeight = QtWidgets.QLineEdit(parent=self.widget)
        self.finalWeight.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.finalWeight.setFont(font)
        self.finalWeight.setObjectName("finalWeight")
        self.gridLayout.addWidget(self.finalWeight, 6, 1, 1, 1)
        self.totalPrice = QtWidgets.QLineEdit(parent=self.widget)
        self.totalPrice.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.totalPrice.setFont(font)
        self.totalPrice.setObjectName("totalPrice")
        self.gridLayout.addWidget(self.totalPrice, 7, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(parent=AddBuyer)
        self.widget1.setGeometry(QtCore.QRect(150, 420, 271, 68))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cancelBtn = QtWidgets.QPushButton(parent=self.widget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.cancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.gridLayout_2.addWidget(self.cancelBtn, 0, 1, 1, 1)
        self.addBtn = QtWidgets.QPushButton(parent=self.widget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.addBtn.setFont(font)
        self.addBtn.setObjectName("addBtn")
        self.addBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.gridLayout_2.addWidget(self.addBtn, 0, 0, 1, 1)
        self.retranslateUi(AddBuyer)
        QtCore.QMetaObject.connectSlotsByName(AddBuyer)

    def retranslateUi(self, AddBuyer):
        _translate = QtCore.QCoreApplication.translate
        AddBuyer.setWindowTitle(_translate("AddBuyer", "SellerInformation"))
        self.label.setText(_translate("AddBuyer", "*ক্রেতার নাম :"))
        self.label_6.setText(_translate("AddBuyer", "মোবাইল :"))
        self.label_2.setText(_translate("AddBuyer", "*মাছের নাম :"))
        self.weightType.setItemText(0, _translate("AddBuyer", "কেজি"))
        self.weightType.setItemText(1, _translate("AddBuyer", "মন"))
        self.weightType.setItemText(2, _translate("AddBuyer", "ঠুয়া"))
        self.label_5.setText(_translate("AddBuyer", "কাঁচা (KG.gram) :"))
        self.label_7.setText(_translate("AddBuyer", "পাকা (KG.gram) :"))
        self.label_8.setText(_translate("AddBuyer", "*মোট দাম :"))
        self.label_3.setText(_translate("AddBuyer", "পরিমাপের ধরণ :"))
        self.label_4.setText(_translate("AddBuyer", "দর :"))
        self.cancelBtn.setText(_translate("AddBuyer", " বাতিল"))
        self.addBtn.setText(_translate("AddBuyer", "ঠিক আছে"))

        # self.weightType.currentIndexChanged.connect(self.calculate_price)
        self.rawWeight.textChanged.connect(self.calculate_price)
        self.addBtn.clicked.connect(lambda:self.handle_name_entry(AddBuyer))

        # ************ Autocomplete *****************************
        self.auto_completer(AddBuyer)
        data_save_signals.data_saved.connect(lambda: self.auto_completer(AddBuyer))
        # *************** end autocomplete *******************************
        self.buyerName.textChanged.connect(lambda :self.make_capital(self.buyerName))

        # final weight change
        self.finalWeight.textEdited.connect(self.final_weight_change)


        self.entry_by = ''
        self.entry_by_username()
        data_save_signals.data_saved.connect(self.entry_by_username)
        self.dhol_amount = ''
        self.dhol_amount_calculation()
        data_save_signals.data_saved.connect(self.dhol_amount_calculation)

    def entry_by_username(self):
        session = self.Session()
        setting = session.query(SettingModel).first()
        self.entry_by = setting.username
        session.close()

    def dhol_amount_calculation(self):
        session = self.Session()
        setting = session.query(SettingModel).first()
        self.dhol_amount = (1/1000) * setting.dhol
        session.close()


    def make_capital(self, element):
        element.textChanged.disconnect()
        element.setText(element.text().title())
        element.textChanged.connect(lambda: self.make_capital(element))

    def calculate_price(self):
        def custom_round(value):
            try:
                return round(float(value) + 0.01)
            except ValueError:
                return 0
        # Determine the weight type based on the selected index
        weight_index = self.weightType.currentIndex()
        weight_type = {0: 'kg', 1: 'mann', 2: 'thuya'}.get(weight_index, 'thuya')

        # If the weight type is 'thuya', no calculation is needed
        if weight_type == 'thuya':
            self.finalWeight.clear()
            self.totalPrice.clear()
            return
        # Retrieve input values
        rate = self.fishRate.text().strip()
        raw_weight = self.rawWeight.text().strip()

        if custom_round(rate) == 0 or custom_round(raw_weight) == 0:
            self.dialog = QtWidgets.QDialog()
            error_dialog = QtWidgets.QMessageBox(self.dialog)
            error_dialog.setIcon(QtWidgets.QMessageBox.Icon.Warning)
            error_dialog.setWindowTitle("Input Error")
            error_dialog.setText("দর ও কাঁচা জিরো থেকে বড় যেকোনো সংখ্যা হতে হবে..")  # Rate and weight must be numeric
            error_dialog.exec()
            return

        # Perform calculations
        try:
            raw_weight = float(raw_weight)
        except:
            raw_weight = 0
        fish_rate = custom_round(rate)

        raw_weight_for_dhol = custom_round(raw_weight)
        dhol = raw_weight_for_dhol * self.dhol_amount  # Deduction for dhol (wastage)
        final_weight = round(raw_weight - dhol, 3)  # take digit
        if weight_type == "kg":
            total_price = custom_round((fish_rate*final_weight) / 10) * 10     # 10 is doing for round figure base 10
        else:
            fish_rate = fish_rate/40  # 40 kg per moon
            total_price = custom_round((fish_rate*final_weight) / 10) * 10     # 10 is doing for round figure base 10

        # Update UI fields
        self.finalWeight.setText(str(final_weight))  # Rounded to 2 decimal places
        self.totalPrice.setText(str(total_price))    # Rounded to 2 decimal places

    def final_weight_change(self):
        def custom_round(value):
            try:
                return round(float(value) + 0.01)
            except ValueError:
                return 0
            # Determine the weight type based on the selected index

        weight_index = self.weightType.currentIndex()
        weight_type = {0: 'kg', 1: 'mann', 2: 'thuya'}.get(weight_index, 'thuya')

        # If the weight type is 'thuya', no calculation is needed
        if weight_type == 'thuya':
            return
        rate = self.fishRate.text().strip()
        final_weight_raw = self.finalWeight.text().strip()
        if custom_round(rate) == 0 or custom_round(final_weight_raw)==0:
            self.dialog = QtWidgets.QDialog()
            error_dialog = QtWidgets.QMessageBox(self.dialog)
            error_dialog.setIcon(QtWidgets.QMessageBox.Icon.Warning)
            error_dialog.setWindowTitle("Input Error")
            error_dialog.setText("দর এবং পাকা জিরো থেকে বড় যেকোনো সংখ্যা হতে হবে..")  # Rate and weight must be numeric
            error_dialog.exec()
            return
        fish_rate = custom_round(rate)
        final_weight = float(final_weight_raw)
        if weight_type == "kg":
            total_price = custom_round((fish_rate*final_weight) / 10) * 10     # 10 is doing for round figure base 10
        else:
            fish_rate = fish_rate/40  # 40 kg per moon
            total_price = custom_round((fish_rate*final_weight) / 10) * 10     # 10 is doing for round figure base 10
        self.totalPrice.setText(str(total_price))

    def get_all_names(self):
        """Fetch all seller names from the database for autocomplete."""
        session = self.Session()
        name_entires = session.query(BuyerProfileModel).all()     # change Model name
        session.close()
        return [name_entry.buyer_name for name_entry in name_entires]    # change field name

    def auto_completer(self, AddBuyer):
        """Refresh the QCompleter with the latest seller names."""
        self.all_name = self.get_all_names()
        self.completer = QtWidgets.QCompleter(self.all_name, AddBuyer)  # # QT object parameter AddBuyer
        self.completer.setCaseSensitivity(Qt.CaseSensitivity.CaseInsensitive)
        self.buyerName.setCompleter(self.completer)   # change input field

    def handle_name_entry(self, AddBuyer):
        target_name = self.buyerName.text().strip()  # Change input field
        phone = self.mobile.text().strip()

        if not target_name:
            # QtWidgets.QMessageBox.warning(AddBuyer, "Input Error", "ক্রেতার নাম লিখুন দয়া করে..")
            return False, "ক্রেতার নাম লিখুন দয়া করে.."

        if self.name_exists(target_name):
            print(f"Existing Seller: Seller '{target_name}' already exists. Selected.")
        else:
            # Add the new seller to the database
            if not phone:
                # QtWidgets.QMessageBox.warning(AddBuyer, "Input Error", "নতুন ক্রেতার জন্য ফোন নম্বর যোগ করুন.")
                return False, "নতুন ক্রেতার জন্য ফোন নম্বর যোগ করুন."
            self.add_name(target_name, phone)
            print(f"New Seller: Seller '{target_name}' has been added.")

        # self.auto_completer(AddBuyer)  # Refresh completer with updated list
        data_save_signals.data_saved.emit()  # Send signal to save data
        return True, None

    def name_exists(self, name):
        """Check if the seller exists in the database."""
        session = self.Session()
        exists = session.query(BuyerProfileModel).filter(BuyerProfileModel.buyer_name == name).first() is not None  # Change Model & Field name
        session.close()
        return exists

    def add_name(self, name, phone):
        """Add a new seller to the database."""
        session = self.Session()
        new_name = BuyerProfileModel(buyer_name=name, phone=phone, date=datetime.now(), entry_by=self.entry_by)  # Change Model name & Field Name
        try:
            session.add(new_name)
            session.commit()
        except Exception as e:
            session.rollback()
            QtWidgets.QMessageBox.warning(None, "Database Error", f"Failed to add seller: {e}")
        finally:
            session.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddBuyer = QtWidgets.QDialog()
    ui = Ui_AddBuyer()
    ui.setupUi(AddBuyer)
    AddBuyer.show()
    sys.exit(app.exec())
