# Form implementation generated from reading ui file 'UI/cost_entry.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt, QDate
from datetime import datetime
from models import SellerProfileModel, BuyerProfileModel, LoanModel
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base

class Ui_CostEntry(object):
    def setupUi(self, AddBuyer):

        # ****************** Declear database ************************
        self.Base = declarative_base()
        self.engine = create_engine('sqlite:///business.db')    # change db url
        self.Base.metadata.create_all(self.engine)
        self.Session = sessionmaker(bind=self.engine)
        # ******************* end db ***************************



        AddBuyer.setObjectName("AddBuyer")
        AddBuyer.resize(491, 497)
        AddBuyer.setStyleSheet("""QLineEdit, QDateEdit{border-radius:10px;
                                                      border:1px solid #B8B8B8;
                                                      padding:3px;}
                                  QPushButton{background-color:#2D221B;
                                              color:white;
                                              padding:5px 12px;
                                              border-radius:9px;}
                                QComboBox{border-radius:10px;
                                background:#E1E1E1;
                                border:1px solid #B8B8B8;
                                padding:3px;}
                                QDateEdit{border:1px solid #B8B8B8;border-radius:5px;}
                                QDateEdit::drop-down{
                                            image: url('./images/down-arrow.png');
                                            margin:3px 4px 0 0;
                                            border:1px solid #DEDEDE;
                                           }
                                """)
        self.layoutWidget = QtWidgets.QWidget(parent=AddBuyer)
        self.layoutWidget.setGeometry(QtCore.QRect(62, 22, 361, 391))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.receiverName = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.receiverName.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.receiverName.setFont(font)
        self.receiverName.setObjectName("receiverName")
        self.gridLayout.addWidget(self.receiverName, 2, 1, 1, 1)
        self.payerName = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.payerName.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.payerName.setFont(font)
        self.payerName.setObjectName("payerName")
        self.gridLayout.addWidget(self.payerName, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.amount = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.amount.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.amount.setFont(font)
        self.amount.setObjectName("amount")
        self.gridLayout.addWidget(self.amount, 4, 1, 1, 1)
        self.entryName = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.entryName.setEnabled(True)
        self.entryName.setMinimumSize(QtCore.QSize(210, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.entryName.setFont(font)
        self.entryName.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.entryName.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.entryName.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.entryName.setAutoFillBackground(False)
        self.entryName.setStyleSheet("")
        self.entryName.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.entryName.setIconSize(QtCore.QSize(24, 24))
        self.entryName.setFrame(True)
        self.entryName.setObjectName("entryName")
        self.entryName.addItem("")
        self.entryName.addItem("")
        self.entryName.addItem("")
        self.entryName.addItem("")
        self.entryName.addItem("")
        self.entryName.addItem("")
        self.entryName.addItem("")
        self.entryName.addItem("")
        self.entryName.addItem("")
        self.entryName.addItem("")
        self.entryName.addItem("")
        self.gridLayout.addWidget(self.entryName, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.entryDate = QtWidgets.QDateEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.entryDate.setFont(font)
        self.entryDate.setCalendarPopup(True)
        self.entryDate.setObjectName("entryDate")
        self.gridLayout.addWidget(self.entryDate, 3, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(parent=AddBuyer)
        self.layoutWidget1.setGeometry(QtCore.QRect(150, 420, 271, 68))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cancelBtn = QtWidgets.QPushButton(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.gridLayout_2.addWidget(self.cancelBtn, 0, 1, 1, 1)
        self.addBtn = QtWidgets.QPushButton(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.addBtn.setFont(font)
        self.addBtn.setObjectName("addBtn")
        self.gridLayout_2.addWidget(self.addBtn, 0, 0, 1, 1)

        self.retranslateUi(AddBuyer)
        QtCore.QMetaObject.connectSlotsByName(AddBuyer)

    def retranslateUi(self, AddBuyer):
        _translate = QtCore.QCoreApplication.translate
        AddBuyer.setWindowTitle(_translate("AddBuyer", "এন্ট্রি"))
        self.label_4.setText(_translate("AddBuyer", "প্রদানকারী নাম :"))
        self.label_8.setText(_translate("AddBuyer", "পরিমাণ :"))
        self.label_3.setText(_translate("AddBuyer", "এন্ট্রি নাম"))
        self.label_5.setText(_translate("AddBuyer", "গ্রহণকারীর নাম :"))
        self.entryName.setItemText(0, _translate("AddBuyer", "বিক্রেতা কে প্রদান"))
        self.entryName.setItemText(1, _translate("AddBuyer", "ক্রেতা থেকে গ্রহণ"))
        self.entryName.setItemText(2, _translate("AddBuyer", "মুনাফা উত্তোলন"))
        self.entryName.setItemText(3, _translate("AddBuyer", "মূলধন জমা"))
        self.entryName.setItemText(4, _translate("AddBuyer", "ঋণ গ্রহণ"))
        self.entryName.setItemText(5, _translate("AddBuyer", "ঋণ পরিশোধ"))
        self.entryName.setItemText(6, _translate("AddBuyer", "বেতন / মজুরি প্রদান"))
        self.entryName.setItemText(7, _translate("AddBuyer", "অন্যান্য খরচ"))
        self.entryName.setItemText(8, _translate("costExpenseMain", "মসজিদ/মাদ্রাসা"))
        self.entryName.setItemText(9, _translate("costExpenseMain", "সমিতি"))
        self.entryName.setItemText(10, _translate("costExpenseMain", "অন্যান্য(ভাউচার)"))
        self.label_7.setText(_translate("AddBuyer", "তারিখ :"))
        self.cancelBtn.setText(_translate("AddBuyer", " বাতিল"))
        self.addBtn.setText(_translate("AddBuyer", "ঠিক আছে"))

        # Set current date ****************
        self.entryDate.setDisplayFormat("dd/MM/yyyy")
        self.today_date_raw = datetime.now()
        self.today_date = self.today_date_raw.strftime("%d/%m/%Y").lstrip('0').replace('/0', '/')
        self.qdate_today = QDate.fromString(self.today_date, "d/M/yyyy")
        self.entryDate.setDate(self.qdate_today)

        # ************ Autocomplete Payer Name *****************************
        self.payerCompleter = QtWidgets.QCompleter(self.get_all_payer_names(), AddBuyer)
        self.payerCompleter.setCaseSensitivity(Qt.CaseSensitivity.CaseInsensitive)
        self.payerName.setCompleter(self.payerCompleter)                        # change input field
        # *************** end autocomplete *******************************

        # ************ Autocomplete Receiver Name*****************************
        self.receiverCompleter = QtWidgets.QCompleter(self.get_all_receiver_names(), AddBuyer)
        self.receiverCompleter.setCaseSensitivity(Qt.CaseSensitivity.CaseInsensitive)
        self.receiverName.setCompleter(self.receiverCompleter)

        # change input field
        # *************** end autocomplete *******************************
        self.payerName.textChanged.connect(lambda : self.make_capital(self.payerName))
        self.receiverName.textChanged.connect(lambda : self.make_capital(self.receiverName))

        # autofill amount
        self.receiverCompleter.activated.connect(lambda text: self.autofill_amount(text))
        self.payerCompleter.activated.connect(lambda text: self.autofill_amount(text))

        # disable entry name
        self.entryName.currentIndexChanged.connect(lambda: self.entry_disable(self.entryName.currentIndex()))
        # by default payer name disable cause selected zero index
        self.payerName.setDisabled(True)
        self.payerName.setStyleSheet("background-color: #F0F0F0;")

    def make_capital(self, element):
        element.textChanged.disconnect()
        element.setText(element.text().title())
        element.textChanged.connect(lambda: self.make_capital(element))

    def get_all_payer_names(self):
        """Fetch all seller names from the database for autocomplete."""
        session = self.Session()
        name_entires = session.query(BuyerProfileModel).all()     # change Model name
        session.close()
        return [name_entry.buyer_name for name_entry in name_entires]    # change field name

    def get_all_receiver_names(self):
        """Fetch all seller names from the database for autocomplete."""
        session = self.Session()
        seller_name_entires = session.query(SellerProfileModel).all()     # change Model name
        loan_provider = session.query(LoanModel).filter(LoanModel.amount > 0)
        session.close()
        return [name_entry.seller_name for name_entry in seller_name_entires] + [name_entry.loan_payer_name for name_entry in loan_provider]


    def entry_disable(self, entry_index):
        if entry_index in [0, 2, 5,6, 7, 8 ,9, 10]:
            self.payerName.clear()
            self.amount.clear()
            self.payerName.setDisabled(True)
            self.payerName.setStyleSheet("background-color: #F0F0F0;")
            self.receiverName.setDisabled(False)
            self.receiverName.setStyleSheet("background-color: #FFFFFF;")
        else:
            self.payerName.setDisabled(False)
            self.payerName.setStyleSheet("background-color: #FFFFFF;")
            self.receiverName.clear()
            self.amount.clear()
            self.receiverName.setDisabled(True)
            self.receiverName.setStyleSheet("background-color: #F0F0F0")

    def autofill_amount(self, name):
        entry_index = self.entryName.currentIndex()
        session = self.Session()
        if entry_index == 0:
            seller_name = session.query(SellerProfileModel).filter_by(seller_name=name).first()
            if seller_name:
                self.amount.setText(str(seller_name.total_receivable))
        if entry_index == 1:
            buyer_name = session.query(BuyerProfileModel).filter_by(buyer_name=name).first()
            if buyer_name:
                self.amount.setText(str(buyer_name.total_payable))
        if entry_index == 5:
            loan_payer_name = session.query(LoanModel).filter_by(loan_payer_name=name).first()
            if loan_payer_name:
                self.amount.setText(str(loan_payer_name.amount))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CostEntry = QtWidgets.QDialog()
    ui = Ui_CostEntry()
    ui.setupUi(CostEntry)
    CostEntry.show()
    sys.exit(app.exec())
